security:
  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username

  encoders:
    App\Entity\User:
      algorithm: auto

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    register:
      pattern: ^/api/v1/register
      anonymous: true

    login:
      pattern: ^/api/v1/login
      stateless: true
      anonymous: true
      json_login:
        check_path: api_login
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    api_v1:
      pattern: ^/api/v1
      stateless: true
      provider: app_user_provider
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator

  access_control:
    - { path: ^/api/doc,         roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/v1/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/v1/login,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api,             roles: IS_AUTHENTICATED_FULLY }